name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: kendo-dojo/package-lock.json
        
    - name: Install dependencies
      working-directory: ./kendo-dojo
      run: npm ci
      
    - name: Run TypeScript checks
      working-directory: ./kendo-dojo
      run: npx tsc --noEmit
      
    - name: Run tests
      working-directory: ./kendo-dojo
      run: npm test -- --coverage --watchAll=false
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./kendo-dojo/coverage/lcov.info
        
  build-web:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: kendo-dojo/package-lock.json
        
    - name: Install dependencies
      working-directory: ./kendo-dojo
      run: npm ci
      
    - name: Setup Expo CLI
      run: npm install -g @expo/cli
      
    - name: Build for web
      working-directory: ./kendo-dojo
      run: npm run build:web
      env:
        EXPO_PUBLIC_CONVEX_URL: ${{ secrets.CONVEX_URL }}
        
    - name: Deploy to staging (develop branch)
      if: github.ref == 'refs/heads/develop'
      working-directory: ./kendo-dojo
      run: |
        echo "Deploying to staging environment"
        # Add your staging deployment commands here
        
    - name: Deploy to production (main branch)
      if: github.ref == 'refs/heads/main'
      working-directory: ./kendo-dojo
      run: |
        echo "Deploying to production environment"
        # Add your production deployment commands here
        
  e2e-tests:
    needs: build-web
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: kendo-dojo/package-lock.json
        
    - name: Install dependencies
      working-directory: ./kendo-dojo
      run: npm ci
      
    - name: Install Playwright
      working-directory: ./kendo-dojo
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      working-directory: ./kendo-dojo
      run: npm run test:e2e
      env:
        BASE_URL: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_URL || secrets.STAGING_URL }}
        
    - name: Upload Playwright report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: kendo-dojo/playwright-report/
        retention-days: 30